# Choose a default "cargo run" tool.
# probe-run is recommended if you have a debugger
# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
[target.riscv32i-unknown-none-elf]
runner = "probe-run --chip RP2040"
# runner = "elf2uf2-rs -d"

rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-g",
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
]
[build]
target = "riscv32i-unknown-none-elf"

[env]
DEFMT_LOG = "debug"
